// Generated by CoffeeScript 1.3.3
(function() {

  window.candidates || (window.candidates = [
    {
      firstName: 'David',
      lastName: "Bowie",
      favoriteColor: 'blue',
      tags: ['rock & pop', 'vocals']
    }, {
      firstName: 'Justin',
      lastName: "Timberlake",
      favoriteColor: 'red',
      tags: ['rock & pop', 'vocals']
    }, {
      firstName: 'Debbie',
      lastName: 'Harry',
      favoriteColor: 'green',
      tags: ['rock & pop', 'vocals']
    }, {
      firstName: 'Aretha',
      lastName: 'Franklin',
      favoriteColor: 'beige',
      tags: ['soul', 'vocals']
    }, {
      firstName: 'John',
      lastName: 'Coltrane',
      favoriteColor: 'blue',
      tags: ['jazz', 'sax']
    }, {
      firstName: 'Elvis',
      lastName: 'Costello',
      favoriteColor: 'green',
      tags: ['rock & pop', 'vocals', 'guitar']
    }, {
      firstName: 'Robert',
      lastName: 'Johnson',
      favoriteColor: 'purple',
      tags: ['blues', 'vocals', 'guitar']
    }, {
      firstName: 'Peter',
      lastName: 'Brötzmann',
      favoriteColor: 'blue',
      tags: ['jazz', 'sax']
    }, {
      firstName: 'Billie',
      lastName: 'Holiday',
      favoriteColor: 'purple',
      tags: ['jazz', 'vocals']
    }, {
      firstName: 'Chalie',
      lastName: 'Parker',
      favoriteColor: 'pink',
      tags: ['jazz', 'sax']
    }, {
      firstName: 'Thelonious',
      lastName: 'Monk',
      favoriteColor: 'green',
      tags: ['jazz', 'piano']
    }, {
      firstName: 'Chalie',
      lastName: 'Christian',
      favoriteColor: 'green',
      tags: ['jazz', 'guitar']
    }, {
      firstName: 'Lionel',
      lastName: 'Hampton',
      favoriteColor: 'blue',
      tags: ['jazz', 'vibes']
    }, {
      firstName: 'Joe',
      lastName: 'Pass',
      favoriteColor: 'blue',
      tags: ['jazz', 'guitar']
    }
  ]);

}).call(this);
