// Generated by CoffeeScript 1.3.3
(function() {
  var Card, FiltersController, Toggle;

  Card = (function() {

    Card.prototype.el = {};

    function Card(publicProperties) {
      this.publicProperties = publicProperties;
    }

    Card.prototype.template = function() {
      return $('#card-template').html();
    };

    Card.prototype.render = function() {
      if (this.el.remove) {
        this.el.remove();
      }
      this.el = $(Mustache.render(this.template(), this.publicProperties));
      return this.applyHandlers();
    };

    Card.prototype.applyHandlers = function() {
      var self;
      self = this;
      return self.el.on('click', 'input[name=chosen]', function(e) {
        self.publicProperties['chosen'] = self.el.find('input[name=chosen]:checked').val();
        return self.el.trigger('card:updated');
      });
    };

    return Card;

  })();

  Toggle = (function() {

    Toggle.state = true;

    function Toggle(el, count) {
      this.el = el;
      this.count = count != null ? count : 0;
      this.target = this.el.data('target');
      this.el.on('click', {
        self: this
      }, this.toggle);
    }

    Toggle.prototype.toggle = function(e) {
      this.state = !this.state;
      e.data.self.el.toggleClass('selected');
      return $('.sidebar').trigger('toggle:clicked', e.data.self);
    };

    return Toggle;

  })();

  FiltersController = (function() {

    function FiltersController(el) {
      var self;
      this.el = el;
      self = this;
      this.filters = [];
      this.el.on('toggle:clicked', {
        self: self
      }, this.update);
      $('.candidates').on('card:updated', function(e) {
        $('.toggle-yes').attr('disabled', self.categorizedAs('yes').length === 0);
        $('.toggle-maybe').attr('disabled', self.categorizedAs('maybe').length === 0);
        $('.toggle-no').attr('disabled', self.categorizedAs('no').length === 0);
        return self.filter();
      });
    }

    FiltersController.prototype.update = function(e, toggle) {
      var filterIndex;
      filterIndex = e.data.self.filters.indexOf(toggle.target);
      if (filterIndex > -1) {
        e.data.self.filters.splice(filterIndex, 1);
      } else {
        e.data.self.filters.push(toggle.target);
      }
      return e.data.self.filter();
    };

    FiltersController.prototype.filter = function() {
      var card, chosenFilters, filter, matchables, matches, tagFilters, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2, _results, _results1;
      chosenFilters = this.filters.filter(function(f) {
        return f.match(/chosen/);
      });
      tagFilters = this.filters.filter(function(f) {
        return f.match(/tag/);
      });
      $('.categories').toggleClass('filtering', chosenFilters.length > 0);
      $('#tags').toggleClass('filtering', tagFilters.length > 0);
      if (chosenFilters.length > 0 || tagFilters.length > 0) {
        _ref = window.cards;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          card = _ref[_i];
          card.el.hide();
          matches = true;
          matchables = card.publicProperties['tags'].concat(card.publicProperties['chosen']);
          _ref1 = this.filters;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            filter = _ref1[_j];
            if (matchables.indexOf(filter.match(/\:(.*)$/)[1]) === -1) {
              matches = false;
              break;
            }
          }
          if (matches) {
            _results.push(card.el.show());
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      } else {
        _ref2 = window.cards;
        _results1 = [];
        for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
          card = _ref2[_k];
          _results1.push(card.el.show());
        }
        return _results1;
      }
    };

    FiltersController.prototype.taggedWith = function(tag) {
      var matches;
      return matches = window.cards.filter(function(card) {
        return card.publicProperties.tags.indexOf(tag) > -1;
      });
    };

    FiltersController.prototype.categorizedAs = function(category) {
      var matches;
      return matches = window.cards.filter(function(card) {
        return card.publicProperties['chosen'] === category;
      });
    };

    return FiltersController;

  })();

  $(function() {
    var candidate, card, count, tag, tags, tmp, toggle, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _results;
    window.cards = (function() {
      var _i, _len, _ref, _results;
      _ref = window.candidates;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        candidate = _ref[_i];
        _results.push(new Card(candidate));
      }
      return _results;
    })();
    _ref = window.cards;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      card = _ref[_i];
      card.render();
      $('.candidates').append(card.el);
    }
    window.toggles = (function() {
      var _j, _len1, _ref1, _results;
      _ref1 = $('.toggle');
      _results = [];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        toggle = _ref1[_j];
        _results.push(new Toggle($(toggle)));
      }
      return _results;
    })();
    window.filtersController = new FiltersController($('.sidebar'));
    tags = [];
    _ref1 = window.candidates;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      candidate = _ref1[_j];
      tags = tags.concat(candidate.tags);
    }
    tags = $.unique(tags);
    _results = [];
    for (_k = 0, _len2 = tags.length; _k < _len2; _k++) {
      tag = tags[_k];
      count = filtersController.taggedWith(tag).length;
      tmp = Mustache.render($('#tag-toggle-template').html(), {
        name: tag,
        count: count
      });
      toggle = new Toggle($(tmp));
      _results.push($('#tags').append($('<li></li>').append(toggle.el)));
    }
    return _results;
  });

}).call(this);
